name: grasp_2cam

dataset_dir: &dataset_dir data
env_runner:
  _target_: diffusion_policy.env_runner.dexmachina_runner.DexMachinaEnvRunner
  dataset_dir: *dataset_dir
  n_test: 1
  test_start_seed: 100000
  max_steps: 100
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
  n_latency_steps: ${n_latency_steps}
  fps: 10
  past_action: ${past_action_visible}
  abs_action: False
  # n_envs: null
  # new: from dexmachina envs
  skip_env: False
  env_kwargs_path: ${home_dir}/devmachina/dexmachina/dataset/murp/${data_name}/${rl_run}/data_env.yaml # need to load this
  state_keys: ${state_keys}
  camera_keys: ${camera_keys}
  vis_camera: null # use the depth input camera for vis
  vis_render_hw: [240, 320] #[256, 256]
  repeat_depth: True
  renderer: rasterizer # batched # rasterizer
  device: cpu
  randomize_camera: False

dataset:
  _target_: diffusion_policy.dataset.dexmachina_datasets.DexmachinaImgDataset
  zarr_path: ${home_dir}/devmachina/dexmachina/dataset/murp/${data_name}/${rl_run}/replay_buffer.zarr
  horizon: ${horizon}
  pad_before: ${eval:'${n_obs_steps}-1+${n_latency_steps}'}
  pad_after: ${eval:'${n_action_steps}-1'}
  seed: 42
  val_ratio: 0.02
  max_train_episodes: null
  state_keys: ${state_keys}
  camera_keys: ${camera_keys}
  n_obs_steps: ${n_obs_steps}
  n_action_steps: ${n_action_steps}
